// export default {
//   login: "john-smilga",
//   id: 42133389,
//   node_id: "MDQ6VXNlcjQyMTMzMzg5",
//   avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
//   gravatar_id: "",
//   url: "https://api.github.com/users/john-smilga",
//   html_url: "https://github.com/john-smilga",
//   followers_url: "https://api.github.com/users/john-smilga/followers",
//   following_url:
//     "https://api.github.com/users/john-smilga/following{/other_user}",
//   gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
//   starred_url:
//     "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
//   subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
//   organizations_url: "https://api.github.com/users/john-smilga/orgs",
//   repos_url: "https://api.github.com/users/john-smilga/repos",
//   events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
//   received_events_url:
//     "https://api.github.com/users/john-smilga/received_events",
//   type: "User",
//   site_admin: false,
//   name: "John Smilga",
//   company: "Coding Addict",
//   blog: "www.johnsmilga.com",
//   location: "Los Angeles",
//   email: null,
//   hireable: null,
//   bio: "Creator of Coding Addict",
//   twitter_username: "john_smilga",
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: "2018-08-06T06:48:23Z",
//   updated_at: "2020-07-08T05:01:32Z",
// };

export default {
  login: "octocat",
  id: 583231,
  node_id: "MDQ6VXNlcjU4MzIzMQ==",
  avatar_url: "https://avatars.githubusercontent.com/u/583231?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/octocat",
  html_url: "https://github.com/octocat",
  followers_url: "https://api.github.com/users/octocat/followers",
  following_url: "https://api.github.com/users/octocat/following{/other_user}",
  gists_url: "https://api.github.com/users/octocat/gists{/gist_id}",
  starred_url: "https://api.github.com/users/octocat/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/octocat/subscriptions",
  organizations_url: "https://api.github.com/users/octocat/orgs",
  repos_url: "https://api.github.com/users/octocat/repos",
  events_url: "https://api.github.com/users/octocat/events{/privacy}",
  received_events_url: "https://api.github.com/users/octocat/received_events",
  type: "User",
  site_admin: false,
  name: "The Octocat",
  company: "@github",
  blog: "https://github.blog",
  location: "San Francisco",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 8,
  public_gists: 8,
  followers: 7578,
  following: 9,
  created_at: "2011-01-25T18:44:36Z",
  updated_at: "2022-10-24T11:21:44Z",
};
